server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # /movies or /directors -> looks for pathName.html
    # try_files: tells nginx to look for other files
    # pathName.html -> directoryWithPathName/ -> /index.html
    #   - index.html has our angular code (just transpiled) which contains the routing instructions
    #   - we are basically telling nginx to try some things that won't work, and then default to what we know WILL work
    location / {
        try_files $uri $uri/ /index.html;
    }
}