
# generic app config file - this will ALWAYS run for every profile
# always runs first. means that any properties set here, can be overridden in the profile-specific configs

spring:
    output:
        ansi:  
            enabled: always

    # another way to set the active profile. Command line argument is usually preferred because it has the highest priority. 
    profiles:
        active: ${APP_PROFILE}

# you can add your own properties in the yml! you will likely see warning in here, but it's ok! 
features:
    get-by-rating: true
    max-movie-results: 20