spring:
    application: 
        name: rabbitmq-publisher

    # configuring RabbitMQ
    rabbitmq:
        host: localhost
        port: 5672          # default port for RabbitMQ

server:
    port: 8083

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        leaseRenewalIntervalInSeconds: 30


# custom properties to use for rabbit mq
exchanges:
    fanout: payment

routing-key: key1234        # password for rabbit mq exchanges

