server:
    port: 8125

spring:
    application:
        name: api-gateway

    cloud:
        gateway:
            server:
                webflux:
                    routes:
                        - id: rabbitmq-subscriber          # must match the application name in the other services
                          uri: lb://rabbitmq-subscriber    # lb:// will route traffic to the built-in spring cloud load balancer
                          predicates:
                            - Path=/accounts/**         # any request to /accounts gets routed to accounts-service 
                          filters:
                            - name: CircuitBreaker      # creates the circuit breaker filter on requests to /accounts
                              args:                     # specify where to navigate to when the circuit breaker pops
                                  name: fallbackController              
                                  fallbackUri: forward:/cache/accounts
                          

                        - id: rabbitmq-publisher          # must match the application name in the other services
                          uri: lb://rabbitmq-publisher    # lb:// will route traffic to the built-in spring cloud load balancer
                          predicates:
                            - Path=/payments/**         # any request to /payments gets routed to payments-service 
                          filters:
                            - name: CircuitBreaker      # creates the circuit breaker filter on requests to /accounts
                              args:                     # specify where to navigate to when the circuit breaker pops
                                  name: fallbackController              
                                  fallbackUri: forward:/cache/payments

                    # can setup security for all services in the gateway since everything has to go through it
                    # just make sure other services are not publicly accessible if your security is only in one spot
                    globalcors:
                        cors-configurations:
                            '[/**]':        # matches every endpoint
                                allowedOrigins: "http://localhost:4200"
                                allowwedMethods:
                                    - GET
                                    - POST
                                    - PUT
                                    - DELETE
                                    - OPTIONS       # allows pre-flight cors requests to come through

