# Deployment: instructions for running your containers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movies-api       # this should match to some template label
  template:
    metadata:
      labels:
        app: movies-api   
    spec:
      containers:
        - name: movies-api    # name your container whatever you want
          image: spring-movies-api:latest 
          ports:
            - containerPort: 8080

# --- is the yml document seperator. lets you have multiple documents in the same file. 
# or you could have a backend-deployment.yml and a backend-service.yml
---

# Services: manage network rules. give your pods a stable ip address. 
#   - act as load balancer to round-robin distribute connections across pods
apiVersion: v1
kind: Service
metadata:
  name: movies-api
spec:
  type: LoadBalancer    # provisions an external IP - makes it so the backend is reachable at localhost:8080
  selector:
    app: movies-api
  ports:
    - port: 8080        # port the service listens to externally
      targetPort: 8080  # port the pod is listening on
