apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-ui       # this should match to some template label
  template:
    metadata:
      labels:
        app: movies-ui   
    spec:
      containers:
        - name: movies-ui    # name your container whatever you want
          image: movies-frontend:latest 
          ports:
            - containerPort: 80     # port 80 for nginx

---

apiVersion: v1
kind: Service
metadata:
  name: movies-ui
spec:
  type: LoadBalancer    # provisions an external IP 
  selector:
    app: movies-ui
  ports:
    - port: 4200        # port the service listens to externally
      targetPort: 80    # port the pod is listening on
