# Secrets are used to hold sensitive configuration details
# same use-case as a ConfigMap, just for sensitive data

# K8s is automaticaly going to base64 decode
#   if you want real encryption, you'd need EncryptionConfiguration in k8s

apiVersion: v1
kind: Secret
metadata:
  name: movies-api-secrets

# Opaque just uses base64 encoding/decoding. It also doesn't check your keys - letting you put whatever values for you keys
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c2E=
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=
